import { association } from '../../../../classes/association';
import { DescriptionAsset } from '../../../../classes/idea/DescriptionAsset';
export const a = association;
// beasts that lords would choose on their banner
// NOTE: if you wanna combine them for humor effects (f.e. "The Whiny Dragon"), then "poor" should not be a misfit
export const majesticBeasts: DescriptionAsset[] = [
    {
        name: 'Deer',
        landRange: [a.mountain, a.forest, a.village, a.city],
        powerFits: [a.druid, a.forest, a.village, a.knight],
    },
    {
        name: 'Lion',
        needsOne: [a.knight, a.rich, a.wealthy, a.desert],
        powerFits: [a.knight, a.rich, a.wealthy, a.desert],
    },
    {
        name: 'Cougar',
        landRange: [a.tropical, a.mountain, a.city],
        needsOne: [a.tropical, a.mountain, a.soldier],
        worksForAssasines: true,
        worksForThiefs: true,
        powerFits: [a.mountain, a.soldier, a.tropical],
    },
    {
        name: 'Gryphon',
        needsOne: [a.knight, a.rich, a.wealthy, a.adventurer, a.wizard],
        powerFits: [a.wizard, a.adventurer, a.rich, a.mountain, a.human],
    },
    {
        name: 'Swan',
        needsOne: [a.knight, a.rich, a.wealthy, a.adventurer, a.wizard],
        misfits: [a.barbarian, a.soldier],
        powerFits: [a.elf, a.knight],
    },
    {
        name: 'Sphinx',
        needsOne: [a.desert, a.adventurer, a.wizard],
        misfits: [a.barbarian, a.soldier],
        powerFits: [a.desert, a.wizard, a.tiefling, a.wizard],
    },
    {
        name: 'Elephant',
        needsOne: [a.desert, a.druid, a.barbarian],
        landRange: [a.desert, a.city, a.haven],
        powerFits: [a.desert, a.druid, a.barbarian],
    },
    {
        name: 'Rhino',
        needsOne: [a.desert, a.druid, a.barbarian],
        landRange: [a.desert, a.city, a.haven],
        powerFits: [a.desert, a.druid, a.barbarian],
    },
    {
        name: 'Beholder',
        needsOne: [a.underdark, a.adventurer, a.wizard],
        powerFits: [a.underdark, a.adventurer, a.wizard],
    },
    {
        name: 'Eagle',
        needsOne: [a.elf, a.mountain],
        powerFits: [a.elf, a.wizard, a.wealthy, a.knight, a.druid],
    },
    {
        name: 'Kraken',
        needs: [a.haven],
        powerFits: [a.rich, a.haven],
        worksForAssasines: true,
    },
    {
        name: 'Whale',
        needs: [a.haven],
        powerFits: [a.haven, a.wealthy],
    },
    {
        name: 'Leviathan',
        needs: [a.haven],
        powerFits: [a.haven],
        worksForAssasines: true,
    },
    {
        name: 'Serpent',
        needs: [a.haven],
        powerFits: [a.haven],
        worksForAssasines: true,
        worksForThiefs: true,
    },
    {
        name: 'Basilisk',
        misfits: [a.underdark, a.haven],
        classRange: [a.adventurer, a.wizard, a.bard],
        powerFits: [a.mountain, a.forest, a.wizard, a.adventurer],
        worksForAssasines: true,
        worksForThiefs: true,
    },
    {
        name: 'Cockatrice',
        misfits: [a.underdark, a.haven],
        classRange: [a.adventurer, a.wizard, a.bard],
        powerFits: [a.mountain, a.forest, a.wizard, a.bard],
        worksForAssasines: true,
        worksForThiefs: true,
    },
    {
        name: 'Octopus',
        needs: [a.haven],
        powerFits: [a.haven],
    },
    {
        name: 'Tiger',
        needsOne: [a.tropical, a.city, a.barbarian],
        powerFits: [a.tropical, a.druid],
    },
    {
        name: 'Pheasant',
        needsOne: [a.forest, a.wealthy, a.druid, a.bard],
        misfits: [a.underdark, a.tropical, a.desert, a.haven],
        powerFits: [a.bard, a.forest, a.wealthy, a.druid],
    },
    {
        name: 'Manticore',
        misfits: [a.underdark, a.village, a.forest],
        powerFits: [a.adventurer, a.mountain, a.wizard],
        worksForAssasines: true,
    },
    {
        name: 'Hydra',
        misfits: [a.underdark, a.village, a.modest],
        powerFits: [a.bard, a.adventurer],
        worksForAssasines: true,
    },
    {
        name: 'Dragon',
        powerFits: [a.rich, a.wizard, a.adventurer, a.bard],
        worksForAssasines: true,
    },
    {
        name: 'Phoenix',
        powerFits: [a.wealthy, a.wizard, a.adventurer, a.bard],
    },
    {
        name: 'Harpy',
        misfits: [a.underdark, a.haven, a.forest],
        worksForAssasines: true,
        worksForThiefs: true,
        powerFits: [a.soldier, a.adventurer, a.mountain],
    },
    {
        name: 'Pegasus',
        misfits: [a.underdark, a.haven, a.modest, a.forest],
        powerFits: [
            a.knight,
            a.adventurer,
            a.mountain,
            a.desert,
            a.bard,
            a.wizard,
            a.elf,
        ],
    },
    {
        name: 'Hippogriff',
        misfits: [a.underdark, a.haven, a.modest, a.forest],
        powerFits: [a.knight, a.adventurer, a.mountain, a.forest, a.human],
    },
    {
        name: 'Roc',
        misfits: [a.underdark, a.haven, a.modest, a.forest],
        worksForAssasines: true,
        worksForThiefs: true,
        powerFits: [a.barbarian, a.bard, a.adventurer, a.mountain, a.desert],
    },
    {
        name: 'Condor',
        misfits: [a.underdark, a.haven, a.modest, a.forest],
        powerFits: [a.druid, a.mountain, a.desert],
        worksForAssasines: true,
    },
    {
        name: 'Stallion',
        misfits: [a.underdark, a.haven],
        powerFits: [a.knight, a.wealthy, a.druid],
    },
    {
        name: 'Bull',
        misfits: [a.underdark, a.haven],
        powerFits: [a.druid, a.tiefling, a.barbarian],
    },
    {
        name: 'Unicorn',
        misfits: [a.underdark, a.haven],
        needsOne: [a.wizard, a.elf, a.adventurer, a.bard],
        powerFits: [a.elf, a.wizard, a.adventurer, a.bard],
    },
    {
        name: 'Centaur',
        needsOne: [a.wizard, a.knight, a.adventurer, a.barbarian, a.bard],
        misfits: [a.underdark, a.haven],
        powerFits: [
            a.mountain,
            a.forest,
            a.wizard,
            a.adventurer,
            a.barbarian,
            a.knight,
        ],
    },
    {
        name: 'Minotaur',
        needsOne: [a.wizard, a.knight, a.adventurer, a.barbarian, a.bard],
        misfits: [a.underdark, a.haven],
        powerFits: [a.mountain, a.forest, a.wizard, a.adventurer, a.barbarian],
    },
    {
        name: 'Cyclops',
        needsOne: [a.adventurer, a.barbarian, a.bard, a.mountain],
        misfits: [a.underdark, a.haven],
        powerFits: [a.mountain, a.wizard, a.adventurer, a.barbarian],
    },
    {
        name: 'Yeti',
        needsOne: [a.adventurer, a.barbarian, a.bard, a.mountain],
        misfits: [a.underdark, a.haven],
        powerFits: [a.mountain, a.bard, a.adventurer, a.barbarian],
    },
    {
        name: 'Bigfoot',
        needsOne: [a.barbarian, a.mountain, a.bard, a.forest],
        misfits: [a.underdark, a.haven],
        powerFits: [a.mountain, a.barbarian, a.forest],
    },
];
