import { association } from '../../classes/association';
import { StructuredTavernFits } from '../../classes/idea/StructuredTavernFits';
const a = association;
// insgesamt: 349
// rich: 85, poor: 85, modest: 95, wealthy: 85, prostitute: 25, thief:15, bounty hunter: 12
// rest: 10-20
const poorIconicFittings: StructuredTavernFits[] = [
    { income: a.poor, land: a.haven },
    { income: a.poor, land: a.city },
    { income: a.poor, land: a.village },
    { income: a.poor, land: a.forest },
    { income: a.poor, land: a.mountain },
    { income: a.poor, land: a.desert },
    { income: a.poor, land: a.haven, race: a.human },
    { income: a.poor, land: a.city, race: a.human },
    { income: a.poor, land: a.village, race: a.human },
    { income: a.poor, land: a.desert, race: a.human },
    { income: a.poor, land: a.forest, race: a.elf },
    { income: a.poor, land: a.city, race: a.elf },
    { income: a.poor, land: a.haven, race: a.elf },
    { income: a.poor, land: a.desert, race: a.elf },
    //
    { income: a.poor, land: a.forest, race: a.halfling },
    { income: a.poor, land: a.city, race: a.halfling },
    //halflings can be found predominatly in rural areas
    { income: a.poor, land: a.village, race: a.halfling },
    { income: a.poor, land: a.village, race: a.halfling },
    { income: a.poor, land: a.village, race: a.halfling },
    //
    { income: a.poor, land: a.forest, race: a.gnome },
    { income: a.poor, land: a.city, race: a.gnome },
    { income: a.poor, land: a.mountain, race: a.gnome },
    { income: a.poor, land: a.underdark, race: a.gnome },
    { income: a.poor, land: a.haven, race: a.gnome },
    { income: a.poor, land: a.city, race: a.dwarf },
    { income: a.poor, land: a.mountain, race: a.dwarf },
    { income: a.poor, land: a.underdark, race: a.dwarf },
    { income: a.poor, land: a.haven, race: a.dwarf },
    { income: a.poor, land: a.city, race: a.dwarf },
    { income: a.poor, land: a.desert, race: a.tiefling },
    { income: a.poor, land: a.desert, race: a.tiefling },
    { income: a.poor, land: a.city, race: a.tiefling },
    { income: a.poor, land: a.haven, race: a.tiefling },
    { income: a.poor, land: a.village, race: a.tiefling },
    //drow can be predominatly found in the underdark
    { income: a.poor, land: a.underdark, race: a.drow },
    { income: a.poor, land: a.underdark, race: a.drow },
    { income: a.poor, land: a.underdark, race: a.drow, class: a.soldier },
    //
    { income: a.poor, land: a.city, race: a.drow },
    { income: a.poor, land: a.haven, race: a.drow },
    //
    { income: a.poor, land: a.haven, special: a.prostitute },
    { income: a.poor, land: a.city, special: a.prostitute },
    { income: a.poor, land: a.village, special: a.prostitute },
    { income: a.poor, land: a.desert, special: a.prostitute },
    { income: a.poor, land: a.tropical, special: a.prostitute },
    { income: a.poor, land: a.haven, special: a.thief },
    { income: a.poor, land: a.city, special: a.thief },
    { income: a.poor, land: a.village, special: a.thief },
    { income: a.poor, land: a.desert, special: a.thief },
    { income: a.poor, land: a.haven, special: a.assasine },
    { income: a.poor, land: a.city, special: a.assasine },
    { income: a.poor, land: a.village, special: a.assasine },
    { income: a.poor, land: a.desert, special: a.assasine },
    { income: a.poor, land: a.haven, class: a.soldier },
    { income: a.poor, land: a.city, class: a.soldier },
    { income: a.poor, land: a.village, class: a.soldier },
    { income: a.poor, land: a.desert, class: a.soldier },
    { income: a.poor, land: a.desert, class: a.adventurer },
    { income: a.poor, land: a.city, class: a.adventurer },
    { income: a.poor, land: a.forest, class: a.adventurer },
    { income: a.poor, land: a.mountain, class: a.adventurer },
    { income: a.poor, land: a.underdark, class: a.adventurer },
    { income: a.poor, land: a.haven, class: a.adventurer },
    { income: a.poor, land: a.village, class: a.adventurer },
    { income: a.poor, land: a.tropical, class: a.adventurer },
    { income: a.poor, land: a.city, class: a.bard },
    { income: a.poor, land: a.forest, class: a.bard },
    { income: a.poor, land: a.mountain, class: a.bard },
    { income: a.poor, land: a.haven, class: a.bard },
    { income: a.poor, land: a.village, class: a.bard },
    { income: a.poor, land: a.tropical, class: a.bard },
    //barbarians can be predominatly found in wild areas
    { income: a.poor, land: a.mountain, class: a.barbarian },
    { income: a.poor, land: a.mountain, class: a.barbarian },
    { income: a.poor, land: a.forest, class: a.barbarian },
    { income: a.poor, land: a.forest, class: a.barbarian },
    //
    { income: a.poor, land: a.village, class: a.barbarian },
    { income: a.poor, land: a.desert, class: a.barbarian },
    //
    //druids can be predominatly found in wild areas
    { income: a.poor, land: a.mountain, class: a.druid },
    { income: a.poor, land: a.mountain, class: a.druid },
    { income: a.poor, land: a.forest, class: a.druid },
    { income: a.poor, land: a.forest, class: a.druid },
    //
    { income: a.poor, land: a.village, class: a.druid },
    { income: a.poor, land: a.desert, class: a.druid },
    //
];

const modestIconicFittings: StructuredTavernFits[] = [
    { income: a.modest, land: a.haven },
    { income: a.modest, land: a.city },
    { income: a.modest, land: a.village },
    { income: a.modest, land: a.haven, race: a.human },
    { income: a.modest, land: a.city, race: a.human },
    { income: a.modest, land: a.village, race: a.human },
    { income: a.modest, land: a.desert, race: a.human },
    { income: a.modest, land: a.forest, race: a.elf },
    { income: a.modest, land: a.city, race: a.elf },
    { income: a.modest, land: a.haven, race: a.elf },
    { income: a.modest, land: a.desert, race: a.elf },
    //
    { income: a.modest, land: a.forest, race: a.halfling },
    { income: a.modest, land: a.city, race: a.halfling },
    //halflings can be found predominatly in rural areas
    { income: a.modest, land: a.village, race: a.halfling },
    { income: a.modest, land: a.village, race: a.halfling },
    { income: a.modest, land: a.village, race: a.halfling },
    //
    { income: a.modest, land: a.forest, race: a.gnome },
    { income: a.modest, land: a.city, race: a.gnome },
    { income: a.modest, land: a.mountain, race: a.gnome },
    { income: a.modest, land: a.underdark, race: a.gnome },
    { income: a.modest, land: a.haven, race: a.gnome },
    { income: a.modest, land: a.city, race: a.dwarf },
    { income: a.modest, land: a.mountain, race: a.dwarf },
    { income: a.modest, land: a.underdark, race: a.dwarf },
    { income: a.modest, land: a.haven, race: a.dwarf },
    { income: a.modest, land: a.city, race: a.dwarf },
    { income: a.modest, land: a.desert, race: a.tiefling },
    { income: a.modest, land: a.desert, race: a.tiefling },
    { income: a.modest, land: a.city, race: a.tiefling },
    { income: a.modest, land: a.haven, race: a.tiefling },
    { income: a.modest, land: a.village, race: a.tiefling },
    //drow can be predominatly found in the underdark
    { income: a.modest, land: a.underdark, race: a.drow, class: a.soldier },
    { income: a.modest, land: a.underdark, race: a.drow },
    { income: a.modest, land: a.underdark, race: a.drow },
    //
    { income: a.modest, land: a.city, race: a.drow },
    { income: a.modest, land: a.haven, race: a.drow },
    //
    { income: a.modest, land: a.haven, special: a.prostitute },
    { income: a.modest, land: a.city, special: a.prostitute },
    { income: a.modest, land: a.village, special: a.prostitute },
    { income: a.modest, land: a.desert, special: a.prostitute },
    { income: a.modest, land: a.tropical, special: a.prostitute },
    { income: a.modest, land: a.haven, special: a.thief },
    { income: a.modest, land: a.city, special: a.thief },
    { income: a.modest, land: a.village, special: a.thief },
    { income: a.modest, land: a.desert, special: a.thief },
    { income: a.modest, land: a.haven, special: a.assasine },
    { income: a.modest, land: a.city, special: a.assasine },
    { income: a.modest, land: a.village, special: a.assasine },
    { income: a.modest, land: a.desert, special: a.assasine },
    { income: a.modest, land: a.haven, class: a.soldier },
    { income: a.modest, land: a.city, class: a.soldier },
    { income: a.modest, land: a.village, class: a.soldier },
    { income: a.modest, land: a.desert, class: a.soldier },
    { income: a.modest, land: a.forest, class: a.soldier },
    { income: a.modest, land: a.desert, class: a.adventurer },
    { income: a.modest, land: a.city, class: a.adventurer },
    { income: a.modest, land: a.forest, class: a.adventurer },
    { income: a.modest, land: a.mountain, class: a.adventurer },
    { income: a.modest, land: a.underdark, class: a.adventurer },
    { income: a.modest, land: a.haven, class: a.adventurer },
    { income: a.modest, land: a.village, class: a.adventurer },
    { income: a.modest, land: a.tropical, class: a.adventurer },
    { income: a.modest, land: a.city, class: a.bard },
    { income: a.modest, land: a.forest, class: a.bard },
    { income: a.modest, land: a.mountain, class: a.bard },
    { income: a.modest, land: a.haven, class: a.bard },
    { income: a.modest, land: a.village, class: a.bard },
    { income: a.modest, land: a.tropical, class: a.bard },
    //barbarians can be predominatly found in wild areas
    { income: a.modest, land: a.mountain, class: a.barbarian },
    { income: a.modest, land: a.mountain, class: a.barbarian },
    { income: a.modest, land: a.forest, class: a.barbarian },
    { income: a.modest, land: a.forest, class: a.barbarian },
    //
    { income: a.modest, land: a.village, class: a.barbarian },
    { income: a.modest, land: a.desert, class: a.barbarian },
    //
    //druids can be predominatly found in wild areas
    { income: a.modest, land: a.mountain, class: a.druid },
    { income: a.modest, land: a.mountain, class: a.druid },
    { income: a.modest, land: a.forest, class: a.druid },
    { income: a.modest, land: a.forest, class: a.druid },
    //
    { income: a.modest, land: a.village, class: a.druid },
    { income: a.modest, land: a.desert, class: a.druid },
    //
    //clerics gather in big numbers predominatly in cities
    { income: a.modest, land: a.city, class: a.cleric },
    { income: a.modest, land: a.city, class: a.cleric },
    { income: a.modest, land: a.city, class: a.cleric },
    //
    { income: a.modest, land: a.village, class: a.cleric },
    { income: a.modest, land: a.forest, class: a.cleric },
    //
    //knights gather in big numbers predominatly in cities
    { income: a.modest, land: a.city, class: a.knight },
    { income: a.modest, land: a.city, class: a.knight },
    { income: a.modest, land: a.city, class: a.knight },
    //
    { income: a.modest, land: a.forest, class: a.knight },
    { income: a.modest, land: a.village, class: a.knight },
    //
    { income: a.modest, land: a.forest, class: a.wizard },
    { income: a.modest, land: a.city, class: a.wizard },
    { income: a.modest, land: a.village, class: a.wizard },
    { income: a.modest, land: a.haven, class: a.wizard },
    { income: a.modest, land: a.desert, class: a.wizard },
];

const wealthyIconicFittings: StructuredTavernFits[] = [
    { income: a.wealthy, land: a.haven },
    { income: a.wealthy, land: a.city },
    { income: a.wealthy, land: a.haven, class: a.adventurer },
    { income: a.wealthy, land: a.city, class: a.adventurer },
    { income: a.wealthy, land: a.village },
    { income: a.wealthy, land: a.haven, race: a.human },
    { income: a.wealthy, land: a.city, race: a.human },
    { income: a.wealthy, land: a.village, race: a.human },
    { income: a.wealthy, land: a.desert, race: a.human },
    { income: a.wealthy, land: a.forest, race: a.elf },
    { income: a.wealthy, land: a.city, race: a.elf },
    { income: a.wealthy, land: a.haven, race: a.elf },
    { income: a.wealthy, land: a.desert, race: a.elf },
    //
    { income: a.wealthy, land: a.forest, race: a.halfling },
    { income: a.wealthy, land: a.city, race: a.halfling },
    //halflings can be found predominatly in rural areas
    { income: a.wealthy, land: a.village, race: a.halfling },
    { income: a.wealthy, land: a.village, race: a.halfling },
    { income: a.wealthy, land: a.village, race: a.halfling },
    //
    { income: a.wealthy, land: a.forest, race: a.gnome },
    { income: a.wealthy, land: a.city, race: a.gnome },
    { income: a.wealthy, land: a.mountain, race: a.gnome },
    { income: a.wealthy, land: a.underdark, race: a.gnome },
    { income: a.wealthy, land: a.haven, race: a.gnome },
    { income: a.wealthy, land: a.city, race: a.dwarf },
    { income: a.wealthy, land: a.mountain, race: a.dwarf },
    { income: a.wealthy, land: a.underdark, race: a.dwarf },
    { income: a.wealthy, land: a.haven, race: a.dwarf },
    { income: a.wealthy, land: a.city, race: a.dwarf },
    { income: a.wealthy, land: a.desert, race: a.tiefling },
    { income: a.wealthy, land: a.desert, race: a.tiefling },
    { income: a.wealthy, land: a.city, race: a.tiefling },
    { income: a.wealthy, land: a.haven, race: a.tiefling },
    { income: a.wealthy, land: a.village, race: a.tiefling },
    //drow can be predominatly found in the underdark
    { income: a.wealthy, land: a.underdark, race: a.drow, class: a.soldier },
    { income: a.wealthy, land: a.underdark, race: a.drow },
    { income: a.wealthy, land: a.underdark, race: a.drow },
    //
    { income: a.wealthy, land: a.city, race: a.drow },
    { income: a.wealthy, land: a.haven, race: a.drow },
    //
    { income: a.wealthy, land: a.haven, special: a.prostitute },
    { income: a.wealthy, land: a.city, special: a.prostitute },
    { income: a.wealthy, land: a.village, special: a.prostitute },
    { income: a.wealthy, land: a.desert, special: a.prostitute },
    { income: a.wealthy, land: a.tropical, special: a.prostitute },
    { income: a.wealthy, land: a.haven, special: a.thief },
    { income: a.wealthy, land: a.city, special: a.thief },
    { income: a.wealthy, land: a.village, special: a.thief },
    { income: a.wealthy, land: a.desert, special: a.thief },
    { income: a.wealthy, land: a.haven, special: a.assasine },
    { income: a.wealthy, land: a.city, special: a.assasine },
    { income: a.wealthy, land: a.village, special: a.assasine },
    { income: a.wealthy, land: a.desert, special: a.assasine },
    { income: a.wealthy, land: a.haven, class: a.soldier },
    { income: a.wealthy, land: a.city, class: a.soldier },
    { income: a.wealthy, land: a.village, class: a.soldier },
    { income: a.wealthy, land: a.desert, class: a.soldier },
    { income: a.wealthy, land: a.forest, class: a.soldier },
    { income: a.wealthy, land: a.desert, class: a.adventurer },
    { income: a.wealthy, land: a.city, class: a.adventurer },
    { income: a.wealthy, land: a.forest, class: a.adventurer },
    { income: a.wealthy, land: a.mountain, class: a.adventurer },
    { income: a.wealthy, land: a.underdark, class: a.adventurer },
    { income: a.wealthy, land: a.haven, class: a.adventurer },
    { income: a.wealthy, land: a.village, class: a.adventurer },
    { income: a.wealthy, land: a.tropical, class: a.adventurer },
    { income: a.wealthy, land: a.city, class: a.bard },
    { income: a.wealthy, land: a.forest, class: a.bard },
    { income: a.wealthy, land: a.mountain, class: a.bard },
    { income: a.wealthy, land: a.haven, class: a.bard },
    { income: a.wealthy, land: a.village, class: a.bard },
    { income: a.wealthy, land: a.tropical, class: a.bard },
    //clerics gather in big numbers predominatly in cities
    { income: a.wealthy, land: a.city, class: a.cleric },
    { income: a.wealthy, land: a.city, class: a.cleric },
    { income: a.wealthy, land: a.city, class: a.cleric },
    //
    { income: a.wealthy, land: a.village, class: a.cleric },
    { income: a.wealthy, land: a.forest, class: a.cleric },
    //
    //knights gather in big numbers predominatly in cities
    { income: a.wealthy, land: a.city, class: a.knight },
    { income: a.wealthy, land: a.city, class: a.knight },
    { income: a.wealthy, land: a.city, class: a.knight },
    //
    { income: a.wealthy, land: a.forest, class: a.knight },
    { income: a.wealthy, land: a.village, class: a.knight },
    //
    { income: a.wealthy, land: a.forest, class: a.wizard },
    { income: a.wealthy, land: a.city, class: a.wizard },
    { income: a.wealthy, land: a.village, class: a.wizard },
    { income: a.wealthy, land: a.haven, class: a.wizard },
    { income: a.wealthy, land: a.desert, class: a.wizard },
];

const richIconicFittings: StructuredTavernFits[] = [
    // vastly rich taverns in villages seem strange. vastly rich taverns in forest/mountain seem more likely, since it is like a "holiday tavern for extravang rich people who enjoy hunting"
    { income: a.rich, land: a.haven, race: a.human },
    { income: a.rich, land: a.city, race: a.human },
    { income: a.rich, land: a.city, race: a.human },
    { income: a.rich, land: a.desert, race: a.human },
    { income: a.rich, land: a.forest, race: a.elf },
    { income: a.rich, land: a.city, race: a.elf },
    { income: a.rich, land: a.haven, race: a.elf },
    { income: a.rich, land: a.desert, race: a.elf },
    //
    { income: a.rich, land: a.forest, race: a.halfling },
    { income: a.rich, land: a.city, race: a.halfling },
    { income: a.rich, land: a.forest, race: a.gnome },
    { income: a.rich, land: a.city, race: a.gnome },
    { income: a.rich, land: a.mountain, race: a.gnome },
    { income: a.rich, land: a.underdark, race: a.gnome },
    { income: a.rich, land: a.haven, race: a.gnome },
    { income: a.rich, land: a.city, race: a.dwarf },
    { income: a.rich, land: a.mountain, race: a.dwarf },
    { income: a.rich, land: a.underdark, race: a.dwarf },
    { income: a.rich, land: a.haven, race: a.dwarf },
    { income: a.rich, land: a.city, race: a.dwarf },
    { income: a.rich, land: a.desert, race: a.tiefling },
    { income: a.rich, land: a.desert, race: a.tiefling },
    { income: a.rich, land: a.city, race: a.tiefling },
    { income: a.rich, land: a.haven, race: a.tiefling },
    { income: a.rich, land: a.city, race: a.tiefling },
    //drow can be predominatly found in the underdark
    { income: a.rich, land: a.underdark, race: a.drow },
    { income: a.rich, land: a.underdark, race: a.drow },
    { income: a.rich, land: a.underdark, race: a.drow },
    //
    { income: a.rich, land: a.city, race: a.drow },
    { income: a.rich, land: a.haven, race: a.drow },
    //
    { income: a.rich, land: a.haven, special: a.prostitute },
    { income: a.rich, land: a.city, special: a.prostitute },
    { income: a.rich, land: a.city, special: a.prostitute },
    { income: a.rich, land: a.desert, special: a.prostitute },
    { income: a.rich, land: a.tropical, special: a.prostitute },
    //!!!! DOUBLED MOST LOGICAL CONNECTIONS FOR VASTLY RICH -  OTHERWISE NOT ENOUGH VASTLY RICH CHOICES
    { income: a.rich, land: a.haven },
    { income: a.rich, land: a.city },
    { income: a.rich, land: a.haven },
    { income: a.rich, land: a.haven, race: a.human },
    { income: a.rich, land: a.city, race: a.human },
    { income: a.rich, land: a.city, race: a.human },
    { income: a.rich, land: a.desert, race: a.human },
    { income: a.rich, land: a.forest, race: a.elf },
    { income: a.rich, land: a.city, race: a.elf },
    { income: a.rich, land: a.haven, race: a.elf },
    { income: a.rich, land: a.desert, race: a.elf },
    //
    { income: a.rich, land: a.forest, race: a.halfling },
    { income: a.rich, land: a.city, race: a.halfling },
    { income: a.rich, land: a.city, race: a.halfling },
    { income: a.rich, land: a.forest, race: a.gnome },
    { income: a.rich, land: a.city, race: a.gnome },
    { income: a.rich, land: a.mountain, race: a.gnome },
    { income: a.rich, land: a.underdark, race: a.gnome },
    { income: a.rich, land: a.city, race: a.dwarf },
    { income: a.rich, land: a.mountain, race: a.dwarf },
    { income: a.rich, land: a.underdark, race: a.dwarf },
    { income: a.rich, land: a.haven, race: a.dwarf },
    { income: a.rich, land: a.desert, race: a.tiefling },
    { income: a.rich, land: a.haven, race: a.tiefling },
    { income: a.rich, land: a.city, race: a.tiefling },
    { income: a.rich, land: a.city, race: a.tiefling },
    //drow can be predominatly found in the underdark
    { income: a.rich, land: a.underdark, race: a.drow },
    { income: a.rich, land: a.underdark, race: a.drow },
    { income: a.rich, land: a.underdark, race: a.drow },
    //
    { income: a.rich, land: a.city, race: a.drow },
    { income: a.rich, land: a.haven, race: a.drow },
    //
    { income: a.rich, land: a.haven, special: a.prostitute },
    { income: a.rich, land: a.city, special: a.prostitute },
    { income: a.rich, land: a.desert, special: a.prostitute },
    { income: a.rich, land: a.tropical, special: a.prostitute },
    //!!!!!!
    { income: a.rich, land: a.haven, special: a.thief },
    { income: a.rich, land: a.city, special: a.thief },
    { income: a.rich, land: a.desert, special: a.thief },
    //
    { income: a.rich, land: a.city, class: a.knight },
    { income: a.rich, land: a.forest, class: a.knight },
    { income: a.rich, land: a.city, class: a.knight },
    //
    { income: a.rich, land: a.city, race: a.adventurer },
    { income: a.rich, land: a.haven, race: a.adventurer },
    { income: a.rich, land: a.forest, race: a.adventurer },
    //
    { income: a.rich, land: a.city, class: a.cleric },
    { income: a.rich, land: a.city, class: a.cleric },
    //
    { income: a.rich, land: a.forest, class: a.wizard },
    { income: a.rich, land: a.city, class: a.wizard },
    { income: a.rich, land: a.haven, class: a.wizard },
    { income: a.rich, land: a.desert, class: a.wizard },
];

export const iconicFittings = [
    ...poorIconicFittings,
    ...modestIconicFittings,
    ...wealthyIconicFittings,
    ...richIconicFittings,
];
