import { association } from '../../../../classes/association';
import { AssetKey } from '../../../../classes/idea/AssetKey/AssetKey';
import { ImpressionIdea } from '../../../../classes/idea/ImpressionIdea';
import { Noticable } from '../../../../classes/idea/Noticable';
import { emptyImpression } from '../emptyImpression';
const a = association;
export const bartenderCharisma: ImpressionIdea[] = [
    new ImpressionIdea({name:"Grumbling",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Warm-hearted",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Generous",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Welcoming aura",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Friendly smiling",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Unfriendly",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Honest",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Nostalgic",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Vulgar attitude",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Impolite",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Depressed",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"In love & dreaming",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Organized & hard-working",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Enlightened & peaceful",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Grimly & fierce",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Tipsy & lazy",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Brave & nobel",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Die-hard attitude",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Mistrusting & careful",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Macabre & witty",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Wise & patient",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Lazy & daydreaming",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Ferocious & wild",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Mysterious & shady",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Mysterious & shady",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Curious & story-loving",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Excentric & chaotic",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Clever, but chaotic",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Intelligent, but unfriendly",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Peaceful & chaotic",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Joyful & singing",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Curious & witty",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Genious & excentric",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Humorous & hectic",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Organized & ambitious",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Elegant & calm",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Art-loving & excentric",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Fashion-loving & witty",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Fashion-loving & excentric",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Music-loving & joyful",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Music-loving & flirty",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Music-loving & flirty",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Gossip-loving & flirty",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Gossip-loving & charismatic",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Quiet & careful",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Tipsy & aggressiv",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Alluring & flirty",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Cute & virtuous",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Sturdy & honest",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Sturdy & story-telling",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Vicious, but charming",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Good-natured & trustful",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Trustful & generous",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Tipsy & generous",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    new ImpressionIdea({name:"Tipsy & benevolent",key:AssetKey.BARTENDER_charisma},[emptyImpression],Noticable.bartender),
    
];