import { Adjective, association } from "../classes/Adjectives";
import { Substantive } from "../classes/Substantive";

const a = association;

export const adjectives = [
  new Adjective("Platinum", [a.dwarf, a.rich, a.nobel]),
  new Adjective("Generous", [a.bard, a.rich, a.dwarf]),
  new Adjective("Elegant", [a.bard, a.rich, a.elf]),
  new Adjective("Diamant", [a.dwarf, a.rich, a.dwarf]),
  new Adjective("Golden", [a.nobel, a.rich, a.dwarf]),
  new Adjective("Rusty", [a.criminal, a.poor]),
  new Adjective("Velvet", [a.bard, a.elf, a.rich, a.prostitute]),
  new Adjective("Silky", [a.bard, a.elf, a.rich, a.prostitute]),
  new Adjective("Twill", [a.village, a.elf, a.halfling]),
  new Adjective("Weaving", [a.worker, a.elf, a.halfling, a.human]),
  new Adjective("Knitting", [a.worker, a.elf, a.halfling, a.human]),
  new Adjective("Dreaming", [a.bard, a.elf, a.human]),
  new Adjective("Extravagant", [a.bard, a.rich, a.dwarf]),
  new Adjective("Lousy", [a.criminal, a.poor]),
  new Adjective("Starving", [a.poor]),
  new Adjective("Pathetic", [a.poor]),
  new Adjective("Rotting", [a.criminal, a.poor]),
  new Adjective("Wooden", [a.criminal, a.poor, a.forest]),
  new Adjective("Not Trustworthy", [a.criminal, a.poor]),
  new Adjective("Cockeyed", [a.criminal, a.poor]),
  new Adjective("Squint-eyed", [a.criminal, a.poor]),
  new Adjective("Happy", []),
  new Adjective("Laughing", []),
  new Adjective("Whining", []),
  new Adjective("Cheering", []),
  new Adjective("Drinking", []),
  new Adjective("Dining", [a.rich, a.nobel]),
  new Adjective("Savoring", [a.rich, a.sophisticated]),
  new Adjective("Feasting", [a.worker, a.village]),
  new Adjective("Eating", [a.worker, a.village]),
  new Adjective("Thirsty", []),
  new Adjective("Hungry", []),
  new Adjective("Sleepy", []),
  new Adjective("Salty", [a.haven]),
  new Adjective("Fishy", [a.haven, a.criminal]),
  new Adjective("Spicy", [a.tropical]),
  new Adjective("Fruity", [a.tropical]),
  new Adjective("Spitting", [a.criminal, a.poor]),
  new Adjective("Moaning", [a.prostitute, a.village]),
  new Adjective("Licking", [a.prostitute, a.village]),
  new Adjective("Kissing", [a.prostitute, a.village]),
  new Adjective("Salacious", [a.prostitute, a.rich]),
  new Adjective("Juicy", [a.prostitute, a.poor]),
  new Adjective("Lascivious", [a.prostitute, a.rich]),
  new Adjective("Wet", [a.prostitute, a.poor]),
  new Adjective("Hard", [a.prostitute, a.poor]),
  new Adjective("Corrupting", [a.prostitute, a.criminal]),
  new Adjective("Perverting", [a.prostitute, a.criminal]),
  new Adjective("Stimulating", [a.prostitute, a.worker]),
  new Adjective("Seducing", [a.prostitute, a.worker]),
  new Adjective("Enticing", [a.prostitute, a.sophisticated]),
  new Adjective("Alluring", [a.prostitute, a.sophisticated, a.rich]),
];

export const substantives = [
  new Substantive("Pheasant", [a.druid, a.nobel, a.forest, a.rich]),
  new Substantive("Guinea Fowl", [a.druid, a.nobel, a.forest, a.rich]),
  new Substantive("Partridges", [a.druid, a.nobel, a.forest, a.rich]),
  new Substantive("Deer", [a.druid, a.nobel, a.forest]),
  new Substantive("Stallion", [a.druid, a.nobel, a.city, a.adventurer]),
  new Substantive("Carriage", [a.nobel, a.adventurer, a.rich]),
  new Substantive("Moose", [a.druid, a.nobel, a.forest]),
  new Substantive("Eagle", [a.druid, a.nobel, a.forest, a.rich]),
  new Substantive("Falcon", [a.druid, a.nobel, a.forest, a.rich]),
  new Substantive("Chicken", [a.druid, a.poor, a.forest]),
  new Substantive("Weasel", [a.druid, a.poor, a.forest]),
  new Substantive("Mouse", [a.druid, a.poor, a.forest, a.city]),
  new Substantive("Rat", [a.druid, a.poor, a.criminal, a.city]),
  new Substantive("Cockroach", [a.druid, a.poor, a.criminal, a.city]),
  new Substantive("Snake", [a.druid, a.criminal, a.forest]),
  new Substantive("Butterfly", [a.druid, a.elf, a.forest]),
  new Substantive("Tailor", [a.worker, a.city]),
  new Substantive("Cobbler", [a.worker, a.city]),
  new Substantive("Carpenter", [a.worker, a.city]),
  new Substantive("Weaver", [a.worker, a.village, a.city]),
  new Substantive("Blacksmith", [a.worker, a.city, a.village, a.dwarf]),
  new Substantive("Jeweler", [a.worker, a.rich, a.city, a.dwarf]),
  new Substantive("Potter", [a.worker, a.city, a.village]),
  new Substantive("Butcher", [a.worker, a.village, a.dwarf]),
  new Substantive("Cheese Maker", [a.worker, a.village, a.halfling]),
  new Substantive("Baker", [a.worker, a.village, a.halfling]),
  new Substantive("Brewer", [a.worker, a.village, a.dwarf]),
  new Substantive("Plummer", [a.worker, a.city, a.village, a.poor]),
  new Substantive("Miner", [a.worker, a.mountain, a.underdark, a.dwarf]),
  new Substantive("Wheel", [a.adventurer, a.worker, a.city]),
  new Substantive("Troll", [a.adventurer, a.forest, a.barbarian]),
  new Substantive("Cockatrice", [a.adventurer, a.desert, a.bard]),
  new Substantive("Bugbear", [a.adventurer, a.forest, a.criminal]),
  new Substantive("Hag", [a.adventurer, a.wizard, a.evil]),
  new Substantive("Dragon", [a.adventurer, a.wizard, a.bard, a.dragonborn]),
  new Substantive("Manticore", [a.adventurer, a.wizard, a.mountain]),
  new Substantive("Giant", [a.adventurer, a.mountain, a.barbarian]),
  new Substantive("Goblin", [a.adventurer, a.forest, a.mountain]),
  new Substantive("Imp", [a.adventurer, a.wizard, a.desert, a.evil]),
  new Substantive("Unicorn", [a.adventurer, a.wizard, a.nobel]),
  new Substantive("Mermaid", [a.adventurer, a.prostitute, a.haven]),
  new Substantive("Nymph", [a.adventurer, a.bard, a.prostitute]),
  new Substantive("Satyr", [a.adventurer, a.bard, a.prostitute]),
  new Substantive("Gorgon", [a.adventurer, a.wizard, a.sophisticated]),
  new Substantive("Wolpertinger", [a.adventurer, a.halfling, a.gnome]),
  new Substantive("Gryphon", [a.adventurer, a.wizard, a.nobel]),
  new Substantive("Sphinx", [a.adventurer, a.wizard, a.desert]),
  new Substantive("Merman", [a.adventurer, a.haven, a.bard, a.prostitute]),
  new Substantive("Centaur", [a.adventurer, a.wizard, a.barbarian]),
  new Substantive("Ogre", [a.adventurer, a.barbarian, a.village]),
  new Substantive("Axe", [a.barbarian, a.dwarf, a.dragonborn]),
  new Substantive("Longsword", [a.nobel, a.elf]),
  new Substantive("Quarterstaff", [a.wizard, a.elf, a.cleric]),
  new Substantive("Bow", [a.nobel, a.barbarian, a.elf]),
  new Substantive("Hammer", [a.barbarian, a.dwarf, a.cleric]),
  new Substantive("Spear", [a.elf, a.dragonborn]),
  new Substantive("Shield", [
    a.nobel,
    a.dwarf,
    a.cleric,
    a.dragonborn,
    a.human,
  ]),
  new Substantive("Lance", [a.nobel, a.human]),
  new Substantive("Helmet", [a.nobel, a.elf, a.dwarf, a.cleric]),
  new Substantive("Flail", [a.nobel, a.barbarian, a.dwarf, a.cleric]),
  new Substantive("Claymore", [a.nobel, a.barbarian, a.cleric]),
  new Substantive("Mace", [a.barbarian, a.cleric]),
  new Substantive("Robe", [a.wizard, a.elf, a.cleric]),
  new Substantive("Chain Mail", [a.nobel, a.cleric, a.dragonborn]),
  new Substantive("Cross Bow", [a.dwarf, a.cleric, a.dragonborn]),
  new Substantive("Scepter", [a.wizard, a.cleric, a.gnome]),
  new Substantive("Dagger", [a.halfling, a.criminal, a.dragonborn]),
  new Substantive("Knife", [a.halfling, a.criminal]),
  new Substantive("Saber", [a.haven, a.criminal]),
  new Substantive("Harpune", [a.haven, a.gnome]),
  new Substantive("Net", [a.haven, a.poor]),
  new Substantive("Cutlass", [a.haven, a.criminal]),
  new Substantive("Trident", [a.haven, a.sophisticated]),
  new Substantive("Sextant", [a.haven, a.sophisticated]),
  new Substantive("Anker", [a.haven, a.worker]),
  new Substantive("Steering Wheel", [a.haven, a.worker]),
  new Substantive("Cannon", [a.haven]),
  new Substantive("Rapier", [a.dwarf, a.cleric, a.dragonborn]),
];
