import { association } from "../classes/Adjectives";
import { Substantive, substantiveCategory } from "../classes/Substantive";
const a = association;
const s = substantiveCategory;
export const solidObjects = [
  new Substantive("Wheel", [a.adventurer, a.worker, a.city], s.solid),

  new Substantive("Axe", [a.barbarian, a.dwarf, a.dragonborn], s.solid),
  new Substantive("Longsword", [a.nobel, a.elf, a.adventurer], s.solid),
  new Substantive(
    "Quarterstaff",
    [a.wizard, a.elf, a.cleric, a.druid],
    s.solid
  ),
  new Substantive("Wand", [a.wizard, a.cleric, a.druid], s.solid),
  new Substantive("Composite Bow", [a.nobel, a.barbarian, a.human], s.solid),
  new Substantive("Long Bow", [a.elf, a.forest, a.dragonborn], s.solid),
  new Substantive("Short Bow", [a.city, a.halfling, a.dragonborn], s.solid),
  new Substantive("Slingshot", [a.gnome, a.halfling, a.village], s.solid),
  new Substantive("Hammer", [a.barbarian, a.dwarf, a.cleric], s.solid),
  new Substantive("Spear", [a.elf, a.dragonborn], s.solid),
  new Substantive(
    "Shield",
    [a.nobel, a.dwarf, a.cleric, a.dragonborn, a.human],
    s.solid
  ),
  new Substantive("Lance", [a.nobel, a.human], s.solid),
  new Substantive("Helmet", [a.nobel, a.elf, a.dwarf, a.cleric], s.solid),
  new Substantive("Flail", [a.nobel, a.barbarian, a.dwarf, a.cleric], s.solid),
  new Substantive("Claymore", [a.nobel, a.barbarian, a.cleric], s.solid),
  new Substantive("Mace", [a.barbarian, a.cleric], s.solid),
  new Substantive("Robe", [a.wizard, a.elf, a.cleric, a.druid], s.solid),
  new Substantive("Chain Mail", [a.nobel, a.cleric, a.dragonborn], s.solid),
  new Substantive("Cross Bow", [a.dwarf, a.cleric, a.drow], s.solid),
  new Substantive("Scepter", [a.wizard, a.cleric, a.druid], s.solid),
  new Substantive("Dagger", [a.criminal, a.dragonborn, a.drow], s.solid),
  new Substantive("Knife", [a.halfling, a.criminal, a.drow], s.solid),
  new Substantive("Saber", [a.haven, a.criminal], s.solid),
  new Substantive("Harpune", [a.haven, a.gnome], s.solid),
  new Substantive("Net", [a.haven, a.poor], s.solid),
  new Substantive("Cutlass", [a.haven, a.criminal], s.solid),
  new Substantive("Trident", [a.haven, a.sophisticated], s.solid),
  new Substantive("Sextant", [a.haven, a.sophisticated, a.adventurer], s.solid),
  new Substantive("Anker", [a.haven, a.worker], s.solid),
  new Substantive("Steering Wheel", [a.haven, a.worker], s.solid),
  new Substantive("Cannon", [a.haven], s.solid),
  new Substantive("Rapier", [a.haven, a.bard, a.dragonborn], s.solid),
  new Substantive("Bell", [a.cleric, a.city], s.solid),
  new Substantive("Candle", [a.cleric, a.wizard], s.solid),
  new Substantive("Scroll", [a.cleric, a.wizard], s.solid),
  new Substantive("Temple", [a.cleric, a.druid], s.solid),
  new Substantive("Altar", [a.cleric, a.druid], s.solid),
  new Substantive("Relic", [a.cleric, a.wizard], s.solid),
  new Substantive("Censer", [a.cleric], s.solid),
  new Substantive("Offertory", [a.cleric], s.solid),
  new Substantive("Goblet", [a.wizard, a.cleric], s.solid),
  new Substantive("Chalice", [a.wizard, a.cleric, a.rich], s.solid),
  new Substantive("Tome", [a.wizard, a.cleric], s.solid),
  new Substantive("Grail", [a.wizard, a.cleric, a.nobel], s.solid),
  new Substantive("Saddle", [a.bard, a.nobel], s.solid),
  new Substantive("Banner", [a.nobel, a.human], s.solid),
  new Substantive("Horseshoe", [a.nobel, a.dwarf], s.solid),
  new Substantive("Saddle", [a.nobel, a.human], s.solid),
  new Substantive("Tower", [a.nobel, a.human], s.solid),
  new Substantive("Catapult", [a.nobel, a.gnome, a.barbarian], s.solid),
  new Substantive("Trebuchet", [a.nobel, a.dwarf], s.solid),
  new Substantive("Ram", [a.barbarian, a.dwarf], s.solid),
  new Substantive("Ballista", [a.elf, a.dragonborn], s.solid),
  new Substantive("Gauntlet", [a.nobel, a.human], s.solid),
  new Substantive("Bridle", [a.nobel, a.human], s.solid),
  new Substantive("Nest", [a.druid, a.forest, a.mountain], s.solid),
  new Substantive("Door", [], s.solid),
  new Substantive("Gate", [], s.solid),
  new Substantive("Wall", [], s.solid),
];

// TODO: This should be a new category: "landscape"
//new Substantive("Rock", [a.druid,a.mountain], s.solid),
//new Substantive("Oasis", [a.druid,a.desert], s.solid),
//new Substantive("Dune", [a.druid,a.desert], s.solid),
//new Substantive("Beach", [a.druid,a.desert], s.solid),
