import { association } from '../classes/Adjectives';

export const specialTavernNames = [
    {
        association: association.barbarian,
        names: [
            'Bloody Axe',
            'Raging Minotaur',
            'Mead Fountain',
            'Savage Hunter',
            'Cowardly Wizard',
            'Resting Ogre',
            'Feasting Tribesman',
        ],
    },
    {
        association: association.adventurer,
        names: [
            'Lost Tome',
            "Traveller's Fortune",
            'Golden Mead Jar',
            'Resting Spell Scroll',
            'Anxious Philistine',
            'Whispering Sphinx',
            'Beholding Beholder',
            'Aliba Bar',
        ],
    },
    {
        association: association.bard,
        names: [
            'Dancing Rapier',
            'Whine-Loving Juggler',
            'Virgin Barmaid',
            'Virgin Bartender',
            'Wine Fountain',
            'Stuffy Priest',
            'Passionate Fiddler',
            'Silver Drum',
            'Laughing Backpipes',
        ],
    },
    {
        association: association.city,
        names: [
            'Warm-Hearted Chancellor',
            'Caroling Chimney',
            'Drink Manufacture',
            'Joyful Judge',
            'Incest Hillbilly',
            'Stony Side Walk',
            'Resting Crane',
        ],
    },
    {
        association: association.cleric,
        names: [
            'Blessed Virgin',
            'Candle Of Virtues',
            'Pillars of Wisdom',
            'Childish Heathen',
            'Heaven On Earth',
            'Heavenely Pitcher',
            'Smiling Monk',
            'Bald-Headed Monk',
            'Joyful Priestess',
        ],
    },
    {
        association: association.criminal,
        names: [
            'Tight Lips',
            'Resting Crowbar',
            'Smiling Dagger',
            'Liqueur Fountain',
            'Lousy Police Dog',
            'Silent Whisper',
            'Silent Lamb',
            'Sneaky Bartender',
            'Wines & Whispers',
        ],
    },
    {
        association: association.desert,
        names: [
            'Wondrous Lamp',
            'Empty Hourglass',
            'Purple Turban',
            'Resting Camel',
            'Thirsty Tourist',
            'Grinning Jakal',
            'Black Scorpion',
        ],
    },
    {
        association: association.dragonborn,
        names: [
            'Dancing Blade',
            'Resting Chain Shirt',
            'Roasted Boar',
            'Snot-Nosed Knight',
            'Drunk Archer',
            'Sleepy Spearman',
            'Lucky Vanguard',
        ],
    },
    {
        association: association.drow,
        names: [
            'Venomous Spider',
            'Bare-Naked Male',
            'Submissive Male',
            'Jeweled Web',
            'Tortured High Elf',
            'Broken Wood Elf',
            'Silent Dagger',
            'Black-Hearted Mistress',
            'Relentless Queen',
        ],
    },
    {
        association: association.druid,
        names: [
            'Honey Bear',
            'Busy Bee',
            'Well-Stuffed Pipe',
            'Fabulous Fungus',
            'Lost Townsmen',
            'Womb Of Nature',
            'Mead-Slurping Eagle',
            'Tree Of Resting',
        ],
    },
    {
        association: association.dwarf,
        names: [
            'Resting Pickaxe',
            'Fortune Forge',
            'Malty Tankard',
            'Beer Fountain',
            'Faint-Hearted Elf',
            'Mead Cave',
            'Booze Tunnel',
            'Beard & Beers',
            'Beardy Barmaid ',
        ],
    },
    {
        association: association.elf,
        names: [
            'Nectar Fountain',
            'Ivory Harp',
            'Slumbering Fairy',
            'Mahagony Bow',
            'Stinky Dwarf',
            'Moonlight Castle',
            'Wines & Warmth',
            'Resting Stars',
        ],
    },
    {
        association: association.evil,
        names: [
            'Dark Alley Walk',
            'Sinister Guard',
            'Baleful Coin',
            'Insidious Laughter',
            'Black-Hearted Judge',
            'Final Laughter',
            'Black Stallion',
            'Flickering Candle',
        ],
    },
    {
        association: association.forest,
        names: [
            'Drunken Fox',
            'Resting Boar',
            'Dancing Woodpecker',
            'Ancient Oak',
            'Rabbit Hole',
            'Bear Cave',
            "Hog's Nest",
            'Vigilant Pinetree',
        ],
    },
    {
        association: association.gnome,
        names: [
            'Resting Gear',
            'Playful Charade',
            'Bubbling Beer',
            'Tipsy Giant',
            'Place For Inventions',
            'Giggling Goblin',
            'Roaring Steam Engine',
            'Ticking Clock',
        ],
    },
    {
        association: association.halfling,
        names: [
            'Smiling Sun',
            'Smirking Horse',
            'Buttered Bread',
            'Whiny Ogre',
            'Hungry Hazelnut',
            'Magic Milk Maid',
            'Resting Rainbow',
            'Dancing Straw Hat',
        ],
    },
    {
        association: association.haven,
        names: [
            'Hidden Booty',
            'Ale Fountain',
            'Friendly Flounder',
            'Dancing Lobster',
            'Resting Anchor',
            'Drowning Landlubber',
            'Savoring Shark',
            'Squinting Squid',
        ],
    },
    {
        association: association.human,
        names: [
            'Resting Hound',
            'Dancing Kitty',
            'Tiny Gnome',
            'Tiny Halfling',
            'Resting Carriage',
            'Vodka Fountain',
            'Wonder Bar',
            'Boosting Brewery',
            'Schnitzel Outpost',
        ],
    },
    {
        association: association.mountain,
        names: [
            'Eagle Nest',
            'Thirsty Miner',
            'Humming Cave',
            'Resting Climber',
            'Dizzy Seaman',
            'Drunken Ogre',
            'Ancient Stone Hag',
            'Cycling Cyclops',
        ],
    },
    {
        association: association.nobel,
        names: [
            'Polished Plate Armor',
            'Majestic Stallion',
            'Honorful Mace',
            'Virtuous Hammer',
            'Heroic Vanguard',
            'Shields & Honors',
            'Ham For Heroes',
        ],
    },
    {
        association: association.poor,
        names: [
            'Half-Empty Plate',
            'Cheap Bartender',
            'Holey Sock',
            'Growling Stomach',
            'Forgetful Bailiff',
            'Cheesy Sock',
            'Resting Servant',
            'Itchy Pillow',
            'Wooden Coin',
        ],
    },
    {
        association: association.prostitute,
        names: [
            'Humping Cowgirl',
            'Lustful Oyster',
            'Emptied Nuts',
            'Juicy Lips',
            'Busy Succubus',
            'Glowing Prick',
            'Slippery Nipple',
            'Club 69',
            'Caretaking Nurse',
            'Hot Firefighter',
            'Endless Tongue',
        ],
    },
    {
        association: association.rich,
        names: [
            'Voluptuous Feast',
            'Caviar Plate',
            'Champagne Fountain',
            'Red Carpet',
            'Cashmere Cat',
            'Lobster Palace',
            'Champagne & Caviar',
            'Golden Lobster',
        ],
    },
    {
        association: association.sophisticated,
        names: [
            'Parlament Of Pints',
            'Wine Castle',
            'Paisley Ascot',
            'Ruby Owl',
            "Philosopher's Beard",
            'Dreaming Philantropist',
            'Diligent Scholar',
            'Glimmering Candle',
            'Culture & Cognac',
        ],
    },
    {
        association: association.tiefling,
        names: [
            'Inner Flame',
            'Sarcastic Thinker',
            'Flickering Spark',
            'Malicious Smirker',
            'Horned Watchdog',
            'Macabre Dancer',
            'Devilish Fiddler',
            'Brandy Fountain',
        ],
    },
    {
        association: association.tropical,
        names: [
            'Dancing Coconut',
            'Chatty Parrat',
            'Chilling Monkey',
            'Giggling Cockatoo',
            'Rum Fountain',
            'Tequila Fountain',
            'Sweating Norseman',
            'Dancing Palm Tree',
        ],
    },
    {
        association: association.underdark,
        names: [
            'Dripping Stalagmite',
            'Dancing Mowl',
            'Resting Earthworm',
            'Sleepy Imp',
            'Dancing Dwarf Pit',
            'Tango Tunnel',
            'Underbar',
            'Darkest Beer Brewery',
        ],
    },
    {
        association: association.village,
        names: [
            'Laughing Sheep',
            'Wooden Anvil',
            'Golden Cow',
            'Dancing Farmer',
            'Wimpy City Dweller',
            'Sleeping Hound',
            'Resting Scythe',
            'Brass Plow',
        ],
    },
    {
        association: association.wizard,
        names: [
            'Books & Beverages',
            'Magical Mug',
            'Crystall Bell',
            'Tricking Hat',
            'Fiddling Robe',
            'Smirking Hat',
            'Shots & Scrolls',
            'Wine Fountain',
            'Illiterate Barbarian',
        ],
    },
    {
        association: association.worker,
        names: [
            'Fellow Craftsman',
            'Sweaty Blacksmith',
            'Resting Anvil',
            'Resting Hammer',
            'Silver Nail',
            'Whiskey Fountain',
            'Snot-Nosed Nobleman',
            'Smirking Tailor',
            'Drunken Cobbler',
        ],
    },
];
