import { association } from '../../../classes/association';
import { NameIdea } from '../../../classes/idea/NameIdea';

const a = association;

const VERY_SPECIAL_NAME_PROB = 0.3;
export const specialNames: NameIdea[] = [
    new NameIdea({
        name: 'Bloody Axe',
        needs: [a.barbarian],
        powerFits: [a.barbarian],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'BARbarians',
        needs: [a.barbarian],
        powerFits: [a.barbarian],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Highlander',
        needs: [a.barbarian],
        powerFits: [a.barbarian],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Raging Minotaur',
        needs: [a.barbarian],
        powerFits: [a.barbarian],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: "Khalif's House of (S)Laughter",
        needs: [a.barbarian],
        powerFits: [a.barbarian],
        worksForAssasines: true,
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Kain's Bretzel Pub",
        needs: [a.barbarian],
        powerFits: [a.barbarian],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Mead Fountain',
        needsOne: [a.barbarian, a.dwarf],
        powerFits: [a.barbarian, a.dwarf],
    }),
    new NameIdea({
        name: 'Patient Hunter',
        needs: [a.barbarian],
        powerFits: [a.barbarian],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Feasting Savage',
        needs: [a.barbarian],
        powerFits: [a.barbarian],
    }),
    new NameIdea({
        name: 'Whiny Wizard',
        needs: [a.barbarian],
        powerFits: [a.barbarian],
    }),
    new NameIdea({
        name: 'Grimm Berzerk',
        needs: [a.barbarian],
        powerFits: [a.barbarian],
    }),
    new NameIdea({
        name: 'Feasting Tribesman',
        needs: [a.barbarian],
        powerFits: [a.barbarian],
    }),
    new NameIdea({
        name: "Traveller's Fortune",
        needs: [a.adventurer],
        powerFits: [a.adventurer],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Beholding Beholder',
        needsOne: [a.adventurer, a.wizard, a.underdark],
        powerFits: [a.adventurer, a.wizard, a.underdark],
    }),
    new NameIdea({
        name: 'Aliba Bar',
        needsOne: [a.adventurer, a.desert],
        landRange: [a.desert],
        classRange: [a.adventurer, a.bard],
        powerFits: [a.adventurer, a.desert],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Resting Cape',
        needs: [a.adventurer],
        powerFits: [a.adventurer],
    }),
    new NameIdea({
        name: 'Whispering Sphinx',
        needs: [a.adventurer, a.wizard],
        powerFits: [a.adventurer, a.wizard],
    }),
    new NameIdea({
        name: 'Gossiping Goblin',
        needs: [a.adventurer],
        powerFits: [a.adventurer],
    }),
    new NameIdea({
        name: 'Dancing Rapier',
        needs: [a.bard],
        powerFits: [a.bard],
    }),
    new NameIdea({
        name: "Van Smooch's Loft",
        needsOne: [a.bard, a.prostitute],
        powerFits: [a.bard],
        worksForBrothel: true,
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Dancing Virgin',
        needs: [a.bard],
        powerFits: [a.bard],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Tipsy Virgin',
        needsOne: [a.bard, a.prostitute],
        powerFits: [a.bard],
        worksForBrothel: true,
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'House of Poets',
        needs: [a.bard],
        powerFits: [a.bard],
    }),
    new NameIdea({
        name: 'Joyful Juggler',
        needs: [a.bard],
        powerFits: [a.bard],
    }),
    new NameIdea({
        name: 'Fumbling Fiddler',
        needs: [a.bard],
        powerFits: [a.bard],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Lyre & Lyrics',
        needs: [a.bard],
        powerFits: [a.bard],
    }),
    new NameIdea({
        name: 'Laughing Backpipes',
        needs: [a.bard],
        powerFits: [a.bard],
    }),
    new NameIdea({
        name: 'Caroling Chimney',
        needs: [a.city],
        powerFits: [a.city],
    }),
    new NameIdea({
        name: 'Drink Manufacture',
        needs: [a.city],
        powerFits: [a.city],
    }),
    new NameIdea({
        name: 'Joyful Judge',
        needsOne: [a.city, a.wealthy],
        powerFits: [a.city, a.wealthy],
    }),
    new NameIdea({
        name: 'Pergamon & Pencils',
        needsOne: [a.wizard, a.wealthy],
        powerFits: [a.wizard, a.wealthy],
    }),
    new NameIdea({
        name: 'Incest Hillbilly',
        needs: [a.city],
        powerFits: [a.city],
    }),
    new NameIdea({
        name: 'Resting Crane',
        needsOne: [a.city, a.gnome],
        powerFits: [a.city, a.gnome],
    }),
    new NameIdea({
        name: 'Friends on Fridays',
        needsOne: [a.city],
        powerFits: [a.city],
    }),
    new NameIdea({
        name: 'Blessed Virgin',
        needsOne: [a.cleric],
        powerFits: [a.cleric],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Candles of Virtues',
        needsOne: [a.cleric],
        powerFits: [a.cleric],
    }),
    new NameIdea({
        name: 'Pillars of Wisdom',
        needsOne: [a.cleric, a.desert],
        classRange: [a.adventurer, a.cleric],
        powerFits: [a.cleric, a.desert],
    }),
    new NameIdea({
        name: 'Nurturing Nun',
        needsOne: [a.cleric],
        powerFits: [a.cleric],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Hopeless Heathen',
        needsOne: [a.cleric],
        powerFits: [a.cleric],
    }),
    new NameIdea({
        name: 'Heaven on Earth',
        needsOne: [a.cleric],
        powerFits: [a.cleric],
    }),
    new NameIdea({
        name: 'Smiling Monk',
        needsOne: [a.cleric],
        powerFits: [a.cleric],
    }),
    new NameIdea({
        name: 'Bald-Headed Monk',
        needsOne: [a.cleric],
        powerFits: [a.cleric],
    }),
    new NameIdea({
        name: "Brother Pumbleduff's Pub",
        needsOne: [a.cleric],
        powerFits: [a.cleric],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Sister Tavia's Tavern",
        needsOne: [a.cleric],
        powerFits: [a.cleric],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Bald-Headed Monk',
        needsOne: [a.cleric],
        powerFits: [a.cleric],
    }),
    new NameIdea({
        name: 'Praising Priestess',
        needsOne: [a.cleric],
        powerFits: [a.cleric],
    }),
    new NameIdea({
        name: 'Lousy Dog',
        needsOne: [a.thief, a.poor],
        incomeRange: [a.poor, a.modest],
        powerFits: [a.thief],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Red Moon',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Smooth Criminal',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Nimblebarry's Inn",
        needsOne: [a.thief, a.gnome],
        powerFits: [a.thief, a.gnome],
        worksForThiefs: true,
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Rumbledigger's Inn",
        raceRange: [a.gnome],
        needsOne: [a.underdark, a.gnome],
        powerFits: [a.underdark, a.gnome],
        worksForThiefs: true,
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Slumbering Rooster',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Wines & Whispers',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Winds & Whispers',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
        landRange: [a.desert],
    }),
    new NameIdea({
        name: 'Resting Crowbar',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'One-eyed Warden',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Drunken Watchman',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Sips & Secrets',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Careful Kitty',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Crow Bar',
        needsOne: [a.thief],
        powerFits: [a.thief],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Wondrous Lamp',
        needsOne: [a.desert, a.adventurer],
        landRange: [a.desert],
        classRange: [a.bard, a.adventurer],
        powerFits: [a.desert, a.adventurer],
    }),
    new NameIdea({
        name: 'Empty Hourglass',
        needsOne: [a.desert, a.wizard],
        powerFits: [a.desert, a.wizard],
    }),
    new NameIdea({
        name: 'Happy Hookah',
        needsOne: [a.desert],
        powerFits: [a.desert],
    }),
    new NameIdea({
        name: 'Sultans Of Swing',
        needsOne: [a.desert, a.bard],
        powerFits: [a.desert, a.bard],
    }),
    new NameIdea({
        name: 'Purple Turban',
        needsOne: [a.desert],
        misfits: [a.poor],
        powerFits: [a.desert],
    }),
    new NameIdea({
        name: 'Grey Turban',
        needsOne: [a.desert],
        needs: [a.poor],
        powerFits: [a.desert],
    }),
    new NameIdea({
        name: 'Waving Cactus',
        needsOne: [a.desert],
        powerFits: [a.desert],
    }),
    new NameIdea({
        name: 'Resting Camel',
        landRange: [a.desert],
        needsOne: [a.desert, a.druid],
        powerFits: [a.desert, a.druid],
    }),
    new NameIdea({
        name: 'Thirsty Tourist',
        needsOne: [a.desert],
        powerFits: [a.desert],
    }),
    new NameIdea({
        name: 'Dune Palace',
        needs: [a.desert],
        incomeRange: [a.wealthy, a.rich],
        powerFits: [a.desert, a.rich, a.wealthy],
    }),
    new NameIdea({
        name: 'Grinning Jakal',
        needsOne: [a.desert, a.thief],
        landRange: [a.desert],
        powerFits: [a.desert],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Black Scorpion',
        needsOne: [a.desert, a.assasine],
        powerFits: [a.desert],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Slumbering Sphinx',
        needsOne: [a.desert],
        powerFits: [a.desert],
    }),
    new NameIdea({
        name: 'Mini Pyramid',
        needsOne: [a.desert],
        powerFits: [a.desert],
    }),
    new NameIdea({
        name: 'Resting Chain Shirt',
        needsOne: [a.soldier, a.cleric, a.knight],
        powerFits: [a.soldier, a.cleric, a.knight],
    }),
    new NameIdea({
        name: 'Drunken Archer',
        needsOne: [a.soldier],
        powerFits: [a.soldier],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Sleepy Spearman',
        needsOne: [a.soldier],
        powerFits: [a.soldier],
    }),
    new NameIdea({
        name: 'Lucky Vanguard',
        needsOne: [a.soldier],
        powerFits: [a.soldier],
    }),
    new NameIdea({
        name: 'Shots For Shooters',
        needsOne: [a.soldier],
        powerFits: [a.soldier],
    }),
    new NameIdea({
        name: 'Singing Blade',
        needsOne: [a.soldier, a.bard],
        powerFits: [a.soldier, a.bard],
    }),
    new NameIdea({
        name: 'Beers & Bucklers',
        needsOne: [a.soldier],
        powerFits: [a.soldier],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Roasted Boar',
        needsOne: [a.soldier],
        powerFits: [a.soldier],
    }),
    new NameIdea({
        name: 'Snot-Nosed Knight',
        needsOne: [a.soldier],
        powerFits: [a.soldier],
    }),
    new NameIdea({
        name: 'Patient Hunter',
        needsOne: [a.drow, a.assasine],
        powerFits: [a.drow],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Black Widow',
        needsOne: [a.drow],
        powerFits: [a.drow],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Grey Widow',
        needsOne: [a.drow, a.poor],
        incomeRange: [a.poor],
        powerFits: [a.drow, a.poor],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Lurking Spider',
        needsOne: [a.drow, a.adventurer],
        powerFits: [a.drow],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Submissive Male',
        needsOne: [a.drow],
        powerFits: [a.drow],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Bare-Naked Male',
        needsOne: [a.drow],
        powerFits: [a.drow],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Tortured High Elf',
        needsOne: [a.drow],
        powerFits: [a.drow],
    }),
    new NameIdea({
        name: 'Broken Wood Elf',
        needsOne: [a.drow],
        powerFits: [a.drow],
    }),
    new NameIdea({
        name: 'Sinister Sister',
        needsOne: [a.drow],
        powerFits: [a.drow],
    }),
    new NameIdea({
        name: 'Black-Hearted Mistress',
        needsOne: [a.drow],
        powerFits: [a.drow],
    }),
    new NameIdea({
        name: 'Relentless Queen',
        needsOne: [a.drow],
        powerFits: [a.drow],
    }),
    new NameIdea({
        name: 'Liqueur Fountain',
        misfits: [a.desert],
        needsOne: [a.drow, a.tiefling],
        powerFits: [a.drow, a.tiefling],
    }),
    new NameIdea({
        name: 'Whiskey Web',
        needsOne: [a.drow],
        misfits: [a.desert],
        powerFits: [a.drow],
    }),
    new NameIdea({
        name: 'Three Daggers',
        needsOne: [a.drow, a.thief],
        powerFits: [a.drow],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Busy Bee',
        needsOne: [a.druid],
        powerFits: [a.druid],
    }),
    new NameIdea({
        name: 'Fabulous Fungus',
        needsOne: [a.druid, a.underdark],
        powerFits: [a.druid, a.underdark],
    }),
    new NameIdea({
        name: 'Womb of Nature',
        needsOne: [a.druid],
        powerFits: [a.druid],
    }),
    new NameIdea({
        name: 'Mead-Slurping Bear',
        needsOne: [a.druid],
        powerFits: [a.druid],
    }),
    new NameIdea({
        name: 'Tree Of Resting',
        needsOne: [a.druid, a.forest],
        powerFits: [a.druid, a.forest],
    }),
    new NameIdea({
        name: 'Dancing Deer',
        needsOne: [a.druid],
        powerFits: [a.druid],
    }),
    new NameIdea({
        name: 'Squinting Squirrel',
        needsOne: [a.druid, a.thief],
        powerFits: [a.druid],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Squirting Squirrel',
        needs: [a.prostitute],
        needsOne: [a.druid, a.forest],
        powerFits: [a.druid, a.forest],
        worksForThiefs: true,
    }),
    new NameIdea({
        name: 'Honey Falcon',
        needsOne: [a.druid],
        powerFits: [a.druid],
    }),
    new NameIdea({
        name: 'Honey Pot',
        needsOne: [a.druid, a.forest],
        powerFits: [a.druid, a.forest],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'White Rabbit',
        needsOne: [a.druid],
        powerFits: [a.druid],
    }),
    new NameIdea({
        name: 'Peppermint Pipe',
        needsOne: [a.druid, a.forest],
        powerFits: [a.druid, a.forest],
    }),
    new NameIdea({
        name: 'Pub Of Peacelovers',
        needsOne: [a.druid],
        powerFits: [a.druid],
    }),
    new NameIdea({
        name: 'Fortune Forge',
        needsOne: [a.dwarf, a.modest],
        powerFits: [a.dwarf, a.modest],
    }),
    new NameIdea({
        name: 'Mead Mine',
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
    }),
    new NameIdea({
        name: 'Beer Mine',
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
    }),
    new NameIdea({
        name: 'Beards & Beers',
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Booze Tunnel',
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Beardy Barmaid',
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
    }),
    new NameIdea({
        name: "Bardin's Bar",
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Baldor's Bar",
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Berin's Bar",
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Thulrig's Tavern",
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Ingard's Inn",
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Pulrig's Pub",
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Jolly Jeweler',
        needsOne: [a.dwarf, a.wealthy],
        powerFits: [a.dwarf, a.wealthy],
    }),
    new NameIdea({
        name: 'Poofy Elf',
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
    }),
    new NameIdea({
        name: 'Marble Mountain',
        needsOne: [a.dwarf],
        powerFits: [a.dwarf],
    }),
    new NameIdea({
        name: 'Nectar Fountain',
        needsOne: [a.elf],
        powerFits: [a.elf],
    }),
    new NameIdea({
        name: "Miridan's Chrystal Palace",
        needsOne: [a.elf],
        powerFits: [a.elf],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Helandir's House Of Fine Drinks",
        needsOne: [a.elf],
        powerFits: [a.elf],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Ilmarin's Inn Of Harmony",
        needsOne: [a.elf],
        powerFits: [a.elf],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Slumbering Fairy',
        needsOne: [a.elf],
        powerFits: [a.elf],
    }),
    new NameIdea({ name: 'Ivory Hall', needsOne: [a.elf], powerFits: [a.elf] }),
    new NameIdea({
        name: 'Ebony Temple',
        needsOne: [a.elf],
        powerFits: [a.elf],
    }),
    new NameIdea({
        name: 'Stinky Dwarf',
        needsOne: [a.elf],
        powerFits: [a.elf],
    }),
    new NameIdea({
        name: 'Moonlight Slumber',
        needsOne: [a.elf],
        powerFits: [a.elf],
    }),
    new NameIdea({
        name: 'Wines & Wonders',
        needsOne: [a.elf, a.adventurer],
        powerFits: [a.elf, a.adventurer],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Resting Bow',
        needsOne: [a.elf],
        powerFits: [a.elf],
    }),
    new NameIdea({
        name: 'Twinkling Star',
        needsOne: [a.elf],
        powerFits: [a.elf],
    }),
    new NameIdea({
        name: 'Baleful Broadswoad',
        needsOne: [a.assasine],
        misfits: [a.desert],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Thirsty Executioner',
        needsOne: [a.assasine],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Grim Wolf',
        needsOne: [a.assasine],
        misfits: [a.desert, a.tropical],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Grim Panther',
        needs: [a.assasine, a.tropical],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Grim Jakal',
        needs: [a.assasine, a.desert],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Bounty Bar',
        needsOne: [a.assasine],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Beers & Bounties',
        needsOne: [a.assasine],
        worksForAssasines: true,
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Waiting Gallow',
        needsOne: [a.assasine],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Last Judgement',
        needsOne: [a.assasine],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Tipsy Woodpecker',
        needsOne: [a.forest],
        powerFits: [a.forest],
    }),
    new NameIdea({
        name: 'Ancient Oak',
        needsOne: [a.forest],
        powerFits: [a.forest],
    }),
    new NameIdea({
        name: 'Rabbit Hole',
        needsOne: [a.forest],
        powerFits: [a.forest],
    }),
    new NameIdea({
        name: 'Laughing Fox',
        needsOne: [a.forest],
        powerFits: [a.forest],
    }),
    new NameIdea({
        name: "Hog's Nest",
        needsOne: [a.forest],
        powerFits: [a.forest],
    }),
    new NameIdea({
        name: 'Pints & Pines',
        needsOne: [a.forest],
        powerFits: [a.forest],
    }),
    new NameIdea({
        name: 'Drunken Boar',
        needsOne: [a.forest],
        powerFits: [a.forest],
    }),
    new NameIdea({
        name: 'Bubbling Beer',
        needsOne: [a.gnome],
        powerFits: [a.gnome],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Tipsy Giant',
        needsOne: [a.gnome],
        powerFits: [a.gnome],
    }),
    new NameIdea({
        name: "Picklebilly's Pub",
        needsOne: [a.gnome],
        powerFits: [a.gnome],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Resting Gear',
        needsOne: [a.gnome],
        powerFits: [a.gnome],
    }),
    new NameIdea({
        name: 'Giggling Gnome',
        needsOne: [a.gnome],
        powerFits: [a.gnome],
    }),
    new NameIdea({
        name: 'Ticking Clock',
        needsOne: [a.gnome],
        powerFits: [a.gnome],
    }),
    new NameIdea({
        name: 'Roaring Enginge',
        needsOne: [a.gnome],
        powerFits: [a.gnome],
    }),
    new NameIdea({
        name: 'Innvention',
        needsOne: [a.gnome],
        powerFits: [a.gnome],
    }),
    new NameIdea({
        name: "Mr. Pebblebaker's Pub",
        needsOne: [a.gnome],
        powerFits: [a.gnome],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Mrs. Barrenboomer's Bar",
        needsOne: [a.gnome],
        powerFits: [a.gnome],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Hall of Charades',
        needsOne: [a.gnome],
        powerFits: [a.gnome],
    }),
    new NameIdea({
        name: 'Smiling Sun',
        needsOne: [a.halfling],
        powerFits: [a.halfling],
    }),
    new NameIdea({
        name: "Bucklebarry's Tavern",
        needsOne: [a.halfling, a.village],
        powerFits: [a.halfling, a.village],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Picklebilly's Pub",
        needsOne: [a.halfling],
        powerFits: [a.halfling],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Crying Onion',
        needsOne: [a.halfling, a.village],
        powerFits: [a.halfling, a.village],
    }),
    new NameIdea({
        name: 'Smirking Pony',
        needsOne: [a.halfling],
        powerFits: [a.halfling],
    }),
    new NameIdea({
        name: 'Buttered Bread',
        misfits: [a.desert],
        needsOne: [a.halfling, a.modest],
        powerFits: [a.halfling, a.modest],
    }),
    new NameIdea({
        name: 'Bumpy Bean',
        needsOne: [a.halfling, a.poor],
        powerFits: [a.halfling, a.poor],
    }),
    new NameIdea({
        name: 'Cheering Chickpea',
        needs: [a.desert],
        incomeRange: [a.poor, a.modest],
        raceRange: [a.gnome, a.halfling],
        powerFits: [a.halfling, a.modest, a.desert],
    }),
    new NameIdea({
        name: 'Humble Hummus',
        needs: [a.desert],
        incomeRange: [a.poor, a.modest],
        powerFits: [a.halfling, a.modest, a.desert],
    }),
    new NameIdea({
        name: 'Humble Hazelnut',
        needsOne: [a.halfling],
        powerFits: [a.halfling],
    }),
    new NameIdea({
        name: 'Dancing Straw Hat',
        needsOne: [a.halfling],
        powerFits: [a.halfling],
    }),
    new NameIdea({
        name: 'Singing Salmon',
        needsOne: [a.halfling, a.haven],
        powerFits: [a.halfling, a.haven],
    }),
    new NameIdea({
        name: 'Friends & Family',
        needsOne: [a.halfling],
        powerFits: [a.halfling],
    }),
    new NameIdea({
        name: "Bronzebrand's Bar",
        needsOne: [a.halfling],
        powerFits: [a.halfling],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Brumblebrand's Bar",
        needsOne: [a.halfling],
        powerFits: [a.halfling],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Isenwood's Inn",
        needsOne: [a.halfling],
        powerFits: [a.halfling],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Tiberlynn's Tavern",
        needsOne: [a.halfling],
        powerFits: [a.halfling],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Hidden Booty',
        needsOne: [a.haven],
        worksForBrothel: true,
        worksForThiefs: true,
        powerFits: [a.haven],
    }),
    new NameIdea({
        name: 'Ale Fountain',
        needsOne: [a.haven],
        powerFits: [a.haven],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Friendly Flounder',
        needsOne: [a.haven],
        powerFits: [a.haven],
    }),
    new NameIdea({
        name: 'Dancing Lobster',
        needsOne: [a.haven],
        powerFits: [a.haven],
    }),
    new NameIdea({
        name: 'Resting Anchor',
        needsOne: [a.haven],
        powerFits: [a.haven],
    }),
    new NameIdea({
        name: 'Drowning Landlubber',
        needsOne: [a.haven],
        powerFits: [a.haven],
        misfits: [a.wealthy, a.rich],
    }),
    new NameIdea({
        name: 'Hail To The Ale',
        needsOne: [a.haven],
        powerFits: [a.haven],
    }),
    new NameIdea({
        name: 'Oily Oyster',
        needsOne: [a.haven],
        worksForBrothel: true,
        powerFits: [a.haven],
    }),
    new NameIdea({
        name: 'Shabby Shark',
        needs: [a.haven],
        incomeRange: [a.poor],
        powerFits: [a.haven, a.poor],
    }),
    new NameIdea({
        name: 'Savoring Shark',
        needs: [a.haven],
        misfits: [a.poor],
        worksForAssasines: true,
        powerFits: [a.haven, a.poor],
    }),
    new NameIdea({
        name: 'Squirting Squid',
        needs: [a.haven],
        worksForBrothel: true,
        worksForThiefs: true,
        powerFits: [a.haven],
    }),
    new NameIdea({
        name: "Captain Barnabis' Bar",
        needs: [a.haven],
        powerFits: [a.haven],
        probability: VERY_SPECIAL_NAME_PROB,
        worksForAllCriminals: true,
    }),
    new NameIdea({
        name: "Captain Dorsen's Drinking Hole",
        needsOne: [a.haven],
        misfits: [a.rich, a.wealthy, a.elf],
        powerFits: [a.haven],
        probability: VERY_SPECIAL_NAME_PROB,
        worksForAllCriminals: true,
    }),
    new NameIdea({
        name: "Perry Piper's Pub",
        needs: [a.haven],
        powerFits: [a.haven],
        probability: VERY_SPECIAL_NAME_PROB,
        worksForAllCriminals: true,
    }),
    new NameIdea({
        name: "Admiral Pensington's Pub",
        needs: [a.haven],
        misfits: [a.poor],
        powerFits: [a.haven],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Feasting Hound',
        needs: [a.human],
        powerFits: [a.human],
        worksForThiefs: true,
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Schnitzel Outpost',
        needs: [a.human],
        powerFits: [a.human],
    }),
    new NameIdea({ name: 'Puzzles', needs: [a.human], powerFits: [a.human] }),
    new NameIdea({
        name: 'Rooftop Bar',
        needs: [a.human],
        powerFits: [a.human],
    }),
    new NameIdea({
        name: 'Full House Bar',
        needs: [a.human],
        powerFits: [a.human],
    }),
    new NameIdea({
        name: "Elizabeths's Tavern",
        needs: [a.human],
        powerFits: [a.human],
        probability: VERY_SPECIAL_NAME_PROB,
        worksForBrothel: true,
    }),
    new NameIdea({
        name: "Paul Paulsen's Pub",
        needs: [a.human],
        powerFits: [a.human],
        probability: VERY_SPECIAL_NAME_PROB,
        worksForAllCriminals: true,
    }),
    new NameIdea({
        name: 'Tipsy Tavern',
        needs: [a.human],
        powerFits: [a.human],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'On The Rocks',
        needs: [a.human],
        powerFits: [a.human],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Bottoms Up!',
        needs: [a.human],
        powerFits: [a.human],
        worksForAllCriminals: true,
    }),
    new NameIdea({
        name: 'Through Thick and Gin',
        needs: [a.human],
        powerFits: [a.human],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: "Inngrid's Inn",
        needs: [a.human],
        powerFits: [a.human],
        probability: VERY_SPECIAL_NAME_PROB,
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Eagle Nest',
        needs: [a.mountain],
        powerFits: [a.mountain],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Busy Miner',
        needs: [a.mountain],
        powerFits: [a.mountain],
    }),
    new NameIdea({
        name: 'Thirsty Climber',
        needs: [a.mountain],
        powerFits: [a.mountain],
    }),
    new NameIdea({
        name: 'Dizzy Seaman',
        needs: [a.mountain],
        powerFits: [a.mountain],
    }),
    new NameIdea({
        name: 'Cycling Cyclops',
        needs: [a.mountain],
        powerFits: [a.mountain],
    }),
    new NameIdea({
        name: 'Stoned Stone Giant',
        needs: [a.mountain],
        powerFits: [a.mountain],
    }),
    new NameIdea({
        name: 'Beer Cave',
        needs: [a.mountain],
        powerFits: [a.mountain],
        misfits: [a.desert],
        worksForAssasines: true,
    }),
    new NameIdea({
        name: 'Majestic Stallion',
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: 'Hall Of Chivalry',
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: "Pure Paladin's Pub",
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: 'Virtuous Hammer',
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: 'Heroic Vanguard',
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: 'Shields & Honors',
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: 'Ham For Heroes',
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: 'Polished Long Sword',
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: 'Pints & Plates',
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: "Percival's Pub",
        needs: [a.knight],
        powerFits: [a.knight],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Victorious Valkyrie',
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: 'Brave Shieldmaiden',
        needs: [a.knight],
        powerFits: [a.knight],
    }),
    new NameIdea({
        name: "Sir Thundersmite's Tavern",
        needs: [a.knight],
        powerFits: [a.knight],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Humping Cowgirl',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Go Home Or Go Hoe',
        needs: [a.prostitute],
        incomeRange: [a.poor, a.modest, a.rich],
        worksForBrothel: true,
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Lust Castle',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Lusty Lion',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Sinful Rose',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Lustful Oyster',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Busy Succubus',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Glowing Prick',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Slippery Nipple',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Nut Suckers',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Venus Flytrap',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Come Right Inn',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Come Together',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Club 69',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Fluet Players',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Horn Blowers',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Pipe Cleaners',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Fox On The Run',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Licking Kitty',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Hot Firefighter',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Smirking Nurse',
        needs: [a.prostitute],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Half-Empty Plate',
        needs: [a.poor],
        powerFits: [a.poor],
    }),
    new NameIdea({ name: 'Holey Sock', needs: [a.poor], powerFits: [a.poor] }),
    new NameIdea({
        name: 'Growling Stomach',
        needs: [a.poor],
        powerFits: [a.poor],
    }),
    new NameIdea({ name: 'Cheesy Sock', needs: [a.poor], powerFits: [a.poor] }),
    new NameIdea({
        name: 'Itchy Pillow',
        needs: [a.poor],
        powerFits: [a.poor],
    }),
    new NameIdea({ name: 'Wooden Coin', needs: [a.poor], powerFits: [a.poor] }),
    new NameIdea({
        name: 'Cheapest Tavern',
        needs: [a.poor],
        powerFits: [a.poor],
    }),
    new NameIdea({ name: 'Grey Mouse', needs: [a.poor], powerFits: [a.poor] }),
    new NameIdea({
        name: 'Smirking Rat',
        needs: [a.poor],
        powerFits: [a.poor],
    }),
    new NameIdea({
        name: 'Hungry Widow',
        needs: [a.poor],
        powerFits: [a.poor],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Caviar Plate',
        needs: [a.rich],
        powerFits: [a.rich],
    }),
    new NameIdea({
        name: "Sir Welfare's Dining House",
        needs: [a.rich],
        powerFits: [a.rich],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({ name: 'Red Carpet', needs: [a.rich], powerFits: [a.rich] }),
    new NameIdea({
        name: 'Cashmere Cat',
        needs: [a.rich],
        powerFits: [a.rich],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Lobster Palace',
        needs: [a.rich],
        powerFits: [a.rich],
    }),
    new NameIdea({
        name: 'Bon Appétit',
        needs: [a.rich],
        powerFits: [a.rich],
    }),
    new NameIdea({
        name: 'Champagne & Caviar',
        needs: [a.rich],
        powerFits: [a.rich],
        worksForBrothel: true,
    }),
    new NameIdea({
        name: 'Golden Oyster',
        needs: [a.rich],
        powerFits: [a.rich],
    }),
    new NameIdea({
        name: 'Duke Of Drinks',
        needs: [a.rich],
        powerFits: [a.rich],
    }),
    new NameIdea({ name: 'Proud Lion', needs: [a.rich], powerFits: [a.rich] }),
    new NameIdea({
        name: 'Hall Of Decadence',
        needs: [a.rich],
        powerFits: [a.rich],
    }),
    new NameIdea({
        name: 'Club Of Debauchery',
        needs: [a.rich],
        powerFits: [a.rich],
    }),
    new NameIdea({
        name: 'Luxury Haven',
        needs: [a.rich],
        powerFits: [a.rich],
    }),
    new NameIdea({
        name: 'Diamonds & Drinks',
        needs: [a.rich],
        powerFits: [a.rich],
    }),
    new NameIdea({
        name: 'Diamonds & Drinks',
        needs: [a.rich],
        powerFits: [a.rich],
    }),
    new NameIdea({
        name: 'Parlament of Pints',
        needs: [a.wealthy],
        powerFits: [a.wealthy],
    }),
    new NameIdea({
        name: 'Wine Castle',
        needs: [a.wealthy],
        powerFits: [a.wealthy],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Paisley Ascot',
        needs: [a.wealthy],
        powerFits: [a.wealthy],
    }),
    new NameIdea({
        name: 'Ruby Owl',
        needs: [a.wealthy],
        powerFits: [a.wealthy],
    }),
    new NameIdea({
        name: 'Diligent Scholar',
        needs: [a.wealthy],
        powerFits: [a.wealthy],
    }),
    new NameIdea({
        name: 'Culture & Cognac',
        needs: [a.wealthy],
        powerFits: [a.wealthy],
    }),
    new NameIdea({
        name: "Philosopher's Beard",
        needs: [a.wealthy],
        powerFits: [a.wealthy],
    }),
    new NameIdea({
        name: "Dr. Rubendrum's Tavern",
        needs: [a.wealthy],
        powerFits: [a.wealthy],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Dapper Inn of Sophistication',
        needs: [a.wealthy],
        powerFits: [a.wealthy],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Infernal Thirst',
        needs: [a.tiefling],
        powerFits: [a.tiefling],
    }),
    new NameIdea({
        name: "Baalzepub's",
        needs: [a.tiefling],
        powerFits: [a.tiefling],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Mrs. Philizer's Pub",
        needs: [a.tiefling],
        powerFits: [a.tiefling],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Mammon's House Of Decadence",
        needs: [a.tiefling],
        powerFits: [a.tiefling],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Baleon's Tavern",
        needs: [a.tiefling],
        powerFits: [a.tiefling],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Fierna's House of Pleasure",
        needs: [a.tiefling, a.prostitute],
        powerFits: [a.tiefling, a.prostitute],
        worksForBrothel: true,
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Izalim's Insidious Inn",
        needs: [a.tiefling],
        powerFits: [a.tiefling],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Sarcastic Thinker',
        needs: [a.tiefling],
        powerFits: [a.tiefling],
    }),
    new NameIdea({
        name: 'Flickering Spark',
        needs: [a.tiefling],
        powerFits: [a.tiefling],
    }),
    new NameIdea({
        name: 'Macabre Dancer',
        needs: [a.tiefling],
        powerFits: [a.tiefling],
    }),
    new NameIdea({
        name: 'Devilish Fiddler',
        needs: [a.tiefling],
        powerFits: [a.tiefling],
    }),
    new NameIdea({
        name: 'Brandy Fountain',
        needs: [a.tiefling],
        powerFits: [a.tiefling],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Lurking Devil',
        needs: [a.tiefling],
        powerFits: [a.tiefling],
    }),
    new NameIdea({
        name: 'Diabolic Dweller',
        needs: [a.tiefling],
        powerFits: [a.tiefling],
    }),
    new NameIdea({
        name: 'Malicious Smirker',
        needs: [a.tiefling],
        powerFits: [a.tiefling],
    }),
    new NameIdea({
        name: 'Jolly Coconut',
        needs: [a.tropical],
        powerFits: [a.tropical],
    }),
    new NameIdea({
        name: 'Chatty Parrot',
        needs: [a.tropical],
        powerFits: [a.tropical],
    }),
    new NameIdea({
        name: 'Chilling Monkey',
        needs: [a.tropical],
        powerFits: [a.tropical],
    }),
    new NameIdea({
        name: 'Giggling Cockatoo',
        needs: [a.tropical],
        powerFits: [a.tropical],
    }),
    new NameIdea({
        name: 'Rum Fountain',
        needs: [a.tropical],
        powerFits: [a.tropical],
    }),
    new NameIdea({
        name: 'Tequila Fountain',
        needs: [a.tropical],
        powerFits: [a.tropical],
    }),
    new NameIdea({
        name: 'Sweating Norseman',
        needs: [a.tropical],
        powerFits: [a.tropical],
    }),
    new NameIdea({
        name: 'Dancing Palm Tree',
        needs: [a.tropical],
        powerFits: [a.tropical],
    }),
    new NameIdea({
        name: 'Dripping Stalagmite',
        needs: [a.underdark],
        powerFits: [a.underdark],
    }),
    new NameIdea({
        name: 'Dancing Mowl',
        needs: [a.underdark],
        powerFits: [a.underdark],
    }),
    new NameIdea({
        name: 'Slumbering Earthworm',
        needs: [a.underdark],
        powerFits: [a.underdark],
    }),
    new NameIdea({
        name: 'Sleepy Imp',
        needs: [a.underdark],
        powerFits: [a.underdark],
    }),
    new NameIdea({
        name: 'Dancing Dwarf Pit',
        needs: [a.underdark],
        powerFits: [a.underdark],
    }),
    new NameIdea({
        name: 'Under Bar',
        needs: [a.underdark],
        powerFits: [a.underdark],
    }),
    new NameIdea({
        name: 'Tipsy Beholder',
        needs: [a.underdark],
        powerFits: [a.underdark],
    }),
    new NameIdea({
        name: 'Down Under',
        needs: [a.underdark],
        powerFits: [a.underdark],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Sharing Sheep',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Gossiping Goose',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Wooden Anvil',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Cuddling Cow',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Jolly Farmer',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Blushing Milkmaid',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Wimpy City Dweller',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Golden Ox',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Resting Pitchfork',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Copper Plow',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Dancing Piglet',
        needs: [a.village],
        powerFits: [a.village],
    }),
    new NameIdea({
        name: 'Books & Beverages',
        needs: [a.wizard],
        powerFits: [a.wizard],
    }),
    new NameIdea({
        name: 'Magical Mug',
        needs: [a.wizard],
        powerFits: [a.wizard],
    }),
    new NameIdea({
        name: 'Fiddling Robe',
        needs: [a.wizard],
        powerFits: [a.wizard],
    }),
    new NameIdea({
        name: 'Tricking Hat',
        needs: [a.wizard],
        powerFits: [a.wizard],
    }),
    new NameIdea({
        name: 'Smirking Hat',
        needs: [a.wizard],
        powerFits: [a.wizard],
    }),
    new NameIdea({
        name: 'Shots & Scrolls',
        needs: [a.wizard],
        powerFits: [a.wizard],
    }),
    new NameIdea({
        name: "Fundalf's Rave Tower",
        needs: [a.wizard],
        powerFits: [a.wizard],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Parry Hotter's Dumble-Bar",
        needs: [a.wizard],
        powerFits: [a.wizard],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Illiterate Barbarian',
        needs: [a.wizard],
        powerFits: [a.wizard],
    }),
    new NameIdea({
        name: "Nordenkainen's Public Sanctum",
        needs: [a.wizard],
        powerFits: [a.wizard],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Yanathar's Bar For Everyone",
        needs: [a.wizard],
        powerFits: [a.wizard],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Meolund's Tiny Pub",
        needs: [a.wizard],
        powerFits: [a.wizard],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: "Numentor's Bar Of Twisted Dimensions",
        needs: [a.wizard],
        powerFits: [a.wizard],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Scared Potter',
        needs: [a.wizard],
        powerFits: [a.wizard],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Resting Anvil',
        needs: [a.modest],
        powerFits: [a.modest],
    }),
    new NameIdea({
        name: 'Cooking Kettle',
        needs: [a.modest],
        powerFits: [a.modest],
    }),
    new NameIdea({
        name: 'Boiling Pot',
        needsOne: [a.modest, a.wizard],
        powerFits: [a.modest, a.wizard],
    }),
    new NameIdea({
        name: 'Beer Fountain',
        needs: [a.modest],
        powerFits: [a.modest],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Tipsy Tailor',
        needs: [a.modest],
        powerFits: [a.modest],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Drunken Cobbler',
        needs: [a.modest],
        powerFits: [a.modest],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Snot-Nosed Noble',
        needs: [a.modest],
        powerFits: [a.modest],
    }),
    new NameIdea({
        name: 'Thirsty Blacksmith',
        needs: [a.modest],
        powerFits: [a.modest],
    }),
    new NameIdea({
        name: "Crafter's Craft Beer Pub",
        needs: [a.modest],
        powerFits: [a.modest],
        misfits: [a.desert],
        probability: VERY_SPECIAL_NAME_PROB,
    }),
    new NameIdea({
        name: 'Ale & Artisans',
        needs: [a.modest],
        powerFits: [a.modest],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Golden Lager',
        needs: [a.modest],
        powerFits: [a.modest],
        misfits: [a.desert],
    }),
    new NameIdea({
        name: 'Crafting Carpenter',
        needs: [a.modest],
        powerFits: [a.modest],
    }),
];
