import { DescriptionAsset } from '../../../../classes/idea/DescriptionAsset';

export const grownWarriorActions: DescriptionAsset[] = [
    { name: 'telling stories about a past crusade' },
    { name: 'telling stories about a battle in the mountains' },
    { name: 'telling stories about a war in the highlands' },
    { name: 'telling stories about a battle in the desert' },
    { name: 'telling stories about a crusade in the desert' },
    { name: 'telling stories about a war on a far-away continent' },
    { name: 'telling stories about the war against the drow' },
    { name: 'telling stories about the war against the dwarves' },
    { name: 'making a toast to a fallen comrade' },
    { name: 'making a toast to a fallen squire' },
    { name: 'making a toast to the royal family' },
    { name: 'making a toast to the gods of justice' },
    { name: 'making a toast to the gods of honor' },
    { name: 'making a toast to his fallen stallion' },
    { name: 'polishing a big claymore' },
    { name: 'polishing a shining armor' },
    { name: 'exchanging war stories at the table' },
    { name: 'exchanging heroic stories with other guests' },
    { name: 'having a drink contest with his squire' },
    { name: 'searching his drunken squire' },
    { name: 'resting from a previous battle' },
    { name: 'transporting secret battle plans' },
    { name: 'showing his muscles in front of a woman' },
];
